### ISSUE TITLE
Force Date or Force DatePlain type not working

### ISSUE THREAD

**Issue by kenny26** [slaveofcode/jkt#2]
For example I have an object like this
```
start: '2018-01-01',
finish: '2018-01-01',
```
with jkt object rule
```
start: Date!
finish: Date!
```
it will return an empty object, with start and finish attribute missing.

However, if I remove the strict (!) rule, it returns expected result with start and finish attribute containing formatted dateTime.

**Comment by slaveofcode** [comment]
Hi @kenny26 this issue was resolved on `v2.3.1`, so I close this issue

You can re-open this issue if the problem still exists on future
